### ISSUE TITLE
date

### ISSUE THREAD

**Issue by Morglaf** [Nicoaedhel/tablet#2]
Il faut pouvoir mettre la date !

**Comment by monsieurhiboux** [comment]
A quoi doit ressembler la data ? JJ/MM/AAAA ? Ou bien JJ/MM ?

**Comment by monsieurhiboux** [comment]
Il y a t'il dans la date un interval ? JJ/MM/AA jusqu'a JJ/MM/AA

**Comment by monsieurhiboux** [comment]
Done !
