### ISSUE TITLE
cadre récapitulatif

### ISSUE THREAD

**Issue by Morglaf** [Nicoaedhel/tablet#3]
un div en bas a gauche (sur l'image) qui récapitule des images sous la form :

"nom de l'image"  8h00 - 10h00 15/02/2009 - 15/02/2009   (ACTIVE)

(la ligne d'une image inactive sont en noir les actives en rouges)

**Comment by monsieurhiboux** [comment]
Tu peux me faire un petit dessin ?

**Comment by Morglaf** [comment]
En fait après avoir aprondie avec mon pére il n'y aura pas de nouvelles
images mais une quinzaine de calque activé ou désactivé celon l'heure et le
jour du coup il on des super nom
genre "R45A Bourgogne"

le cadre est en bas a droite (tout est rouge mais mon pére a des gout de
chiotte)

[image: 0.jpg]

Le mar. 11 oct. 2016 à 15:14, Nicoaedhel notifications@github.com a
écrit :

**Comment by Morglaf** [comment]
discord si tu a besoin

**Comment by monsieurhiboux** [comment]
Fait mais il faut verifier que c'est bien ce que tu voulais.

**Comment by Morglaf** [comment]
c'est parfait ! sauf que cela ne marche que sous firefox... chez moi pas
sous chrome...

Le lun. 17 oct. 2016 à 15:42, Nicoaedhel notifications@github.com a
écrit :

**Comment by Morglaf** [comment]
j'ai sa dans la console : XMLHttpRequest cannot load
file:///E:/1DOS]%20Archivage/1DOS]%20Frais/tablet-master/tablet-master/layers/config.json.
Cross origin requests are only supported for protocol schemes: http, data,
chrome, chrome-extension, https, chrome-extension-resource.send @
jquery-3.1.1.min.js:4

**Comment by monsieurhiboux** [comment]
Il faut le lancer dans un server web

**Comment by Morglaf** [comment]
Et par contre cela ne me marque que les carte active pas celle qui sont
désactivé...

**Comment by Morglaf** [comment]
yep sa marche sur le serveur !!

par contre du coup y'a toujours que les cartes active qui sont affiché pas
celle qui vont étre active...

Le lun. 17 oct. 2016 à 16:01, Nicoaedhel notifications@github.com a
écrit :

**Comment by monsieurhiboux** [comment]
J'ai fait la modif.

**Comment by monsieurhiboux** [comment]
Celle qui vont être active. Ca comprend aussi les dates futurs ? En plus de simplement les heures futur ?

**Comment by monsieurhiboux** [comment]
J'ai mit ça en place. Ca me semble logique. Je close.

**Comment by monsieurhiboux** [comment]
![0](https://cloud.githubusercontent.com/assets/4651441/19443213/54064a2a-948c-11e6-9fc9-b7c233168a47.jpg)

**Comment by Morglaf** [comment]
l'image était incompléte c'était le texte du début de l'issue qui était claire....

**Comment by monsieurhiboux** [comment]
Du coup c'est bon pour toi au niveau du dernier commit ?

**Comment by Morglaf** [comment]
Oui oui nickel je pense que tout est fais et que je t'embéterais plus
jamais avec ce truc ! Merci beaucoup !!!

Le lun. 17 oct. 2016 à 17:22, Nicoaedhel notifications@github.com a
écrit :
